Website/MVC/ViewModels/Catalog.cs
namespace MVC.ViewModels
{
    public class Catalog
    {
        public int PageIndex { get; init; }
        public int PageSize { get; init; }
        public int Count { get; init; }
        public List<CatalogItem> ItemList { get; init; } = null!;
    }
}

Website/MVC/Controllers/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.Models.BasketModels;
using Newtonsoft.Json;
using MVC.Models.CatalogDtos;
using MVC.Services.Interfaces;
using Infrastructure.Exceptions;

namespace MVC.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly IBasketService _basketService;

        public BasketController(ICatalogService catalogService, IBasketService basketService)
        {
            _catalogService = catalogService;
            _basketService = basketService;
        }

        [HttpGet]
        public async Task<IActionResult> AddAsync()
        {
            IEnumerable<CatalogItemDto>? catalogItems;

            try
            {
                catalogItems = await _catalogService.GetAllCatalogItemsAsync();
            }
            catch (BusinessException)
            {
                return View("Error");
            }

            return View(catalogItems);
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync(List<string> items)
        {
            var basketItems = new List<BasketItemDto>();

            foreach (var itemJson in items)
            {
                var item = JsonConvert.DeserializeObject<BasketItemDto>(itemJson);

                if (item is not null)
                {
                    basketItems.Add(item);
                }
            }

            IEnumerable<CatalogItemDto>? catalogItems;

            try
            {
                if (basketItems.Count == 0)
                {
                    ViewData["isAdded"] = false;
                }
                else
                {
                    bool isAdded = await _basketService.AddItemsToBasketAsync(basketItems);

                    ViewData["isAdded"] = isAdded;
                }

                catalogItems = await _catalogService.GetAllCatalogItemsAsync();
            }
            catch (BusinessException)
            {
                return View("Error");
            }

            return View(catalogItems);
        }

        public async Task<IActionResult> ShowAsync()
        {
            IEnumerable<BasketItemDto> basketItems;

            try
            {
                basketItems = await _basketService.GetItemsFromBasketAsync();
            }
            catch (BusinessException)
            {
                return View("Error");
            }

            return View(basketItems);
        }

        public async Task<IActionResult> EmptyAsync()
        {
            try
            {
                await _basketService.EmptyBasketAsync();
            }
            catch (BusinessException)
            {
                return View("Error");
            }

            return RedirectToAction("Show");
        }
    }
}

Website/MVC/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Services.Interfaces;
using MVC.ViewModels;

namespace MVC.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ICatalogService _basketService;

        public CatalogController(ICatalogService catalogService)
        {
            _basketService = catalogService;
        }

        public async Task<IActionResult> Index(
            int? page, int? itemsPage, int? companyFilter, int? genreFilter)
        {
            page ??= 0;
            itemsPage ??= 6;

            var catalog = await _basketService.GetCatalogItemsAsync(
                page.Value, itemsPage.Value, companyFilter, genreFilter);

            if (catalog is null)
            {
                return View("Error");
            }

            var paginationInfo = new PaginationInfo()
            {
                TotalItems = catalog.Count,
                ItemsPerPage = itemsPage.Value,
                CurrentPage = page.Value,
                TotalPages = (int)Math.Ceiling((decimal)catalog.Count / itemsPage.Value)
            };

            var vm = new IndexViewModel()
            {
                CatalogItems = catalog.ItemList,
                Companies = await _basketService.GetCompaniesAsync(),
                Genres = await _basketService.GetGenresAsync(),
                PaginationInfo = paginationInfo
            };

            vm.PaginationInfo.NextPage =
                (vm.PaginationInfo.CurrentPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
            vm.PaginationInfo.PreviousPage =
                (vm.PaginationInfo.CurrentPage == 0) ? "is-disabled" : "";

            return View(vm);
        }
    }
}

Website/MVC/Views/Catalog/BasketAdd.cshtml
@model IEnumerable<CatalogItemDto>

@{
    ViewData["Title"] = "BasketAdd";
}

<form method="post">
    @if (Context.Request.Method == "POST")
    {
        if (ViewData["isAdded"] is not null && (bool)ViewData["isAdded"] ! == true)
        {
            <div style="display: flex; justify-content: space-between; align-items: center; margin-right: 10px;">
                <p style="color: green; font-size: 25px; margin: 0 auto;">Added</p>
                <a asp-controller="Catalog" asp-action="BasketShow">
                    <p style="color: deepskyblue; font-size: 25px; text-align: right; margin: 0;">
                        Show Basket
                    </p>
                </a>
            </div>
        }
        else
        {
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <p style="color: red; font-size: 25px; margin: 0 auto;">Not Added</p>
            </div>
        }
    }
    else
    {
        <div style="display: flex; justify-content: flex-end; align-items: center; margin-right: 10px;">
            <a asp-controller="Catalog" asp-action="BasketShow">
                <p style="color: deepskyblue; font-size: 25px; text-align: right; margin: 0;">
                    Show Basket
                </p>
            </a>
        </div>
    }

    <table class="table">
        <thead>
            <tr>
                <th scope="col"><input type="checkbox" checked="true"/></th>
                <th scope="col">Id</th>
                <th scope="col">Cover</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Year</th>
                <th scope="col">Available Stock</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="items" value='@Json.Serialize(new BasketItemDto { ItemId = item.Id, ItemName = item.Name, ItemPrice = item.Price, ItemPictureUrl = item.PictureUrl, ItemQuantity = 1 })' />
                    </td>
                    <td>
                        <strong>@item.Id</strong>
                    </td>
                    <td>
                        <img src="@item.PictureUrl" alt="@item.Name" width="50" height="50" />
                    </td>
                    <td>
                        <strong>@item.Name</strong>
                    </td>
                    <td>
                        @item.Price.ToString("c", CultureInfo.GetCultureInfo("en-US"))
                    </td>
                    <td>
                        @item.Year
                    </td>
                    <td>
                        @item.AvailableStock
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <input id="add-to-basket" type="submit" value="Add to Basket" class="btn btn-primary" disabled />

    <script>
        // Get the checkboxes and the "Add to Basket" button
        const checkboxes = document.querySelectorAll('input[name="items"]');
        const addToBasketButton = document.querySelector('#add-to-basket');

        // Add a listener for changes to the checkboxes
        checkboxes.forEach((checkbox) => {
            checkbox.addEventListener('change', () => {
                // Check if any checkboxes are checked
                const isChecked = Array.from(checkboxes).some((checkbox) => checkbox.checked);

                // Update the disabled attribute of the "Add to Basket" button
                addToBasketButton.disabled = !isChecked;
            });
        });
    </script>

</form>

Website/MVC/Views/Catalog/BasketShow.cshtml
@model IEnumerable<BasketItemDto>

@{
    ViewData["Title"] = "BasketShow";
    int count = 0;
}
       
<div style="display: flex; justify-content: flex-end; align-items: center; margin-right: 10px;">        
    <a asp-controller="Catalog" asp-action="BasketAdd">
        <p style="color: deepskyblue; font-size: 25px; text-align: right; margin: 0;">
            Add To Basket
        </p>
    </a>
</div>

<table class="table">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Cover</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <strong>@(++count)</strong>
                    </td>
                    <td>
                        <img src="@item.ItemPictureUrl" alt="@item.ItemName" width="50" height="50" />
                    </td>
                    <td>
                        <strong>@item.ItemName</strong>
                    </td>
                    <td>
                        @item.ItemPrice.ToString("c", CultureInfo.GetCultureInfo("en-US"))
                    </td>
                    <td>
                        @item.ItemQuantity
                    </td>
                </tr>
            }
        </tbody>
</table>

@if(Model.Count() > 0)
{
    <form asp-controller="Catalog" asp-action="BasketEmpty" method="post">
    <input type="hidden" name="emptyBasket" value="true" />
    <button type="submit" style="background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;">Empty Basket</button>
    </form>    
} 

Website/MVC/Views/Catalog/Index.cshtml
@model MVC.ViewModels.IndexViewModel

@{
    ViewData["Title"] = "Catalog";
}
<section class="esh-catalog-hero">
    <div class="container">
    </div>
</section>

<section class="esh-catalog-filters">
    <div class="container">
        <form asp-controller="Catalog" asp-action="Index" method="post">
            <label class="esh-catalog-label" data-title="company">
                <select asp-for="@Model.CompanyFilter" asp-items="@Model.Companies" class="esh-catalog-filter"></select>
            </label>
            <label class="esh-catalog-label" data-title="genre">
                <select asp-for="@Model.GenreFilter" asp-items="@Model.Genres" class="esh-catalog-filter"></select>
            </label>
            <input class="esh-catalog-send" type="image" src="~/images/arrow-right.svg" />
            <div class="esh-catalog-basket" style="float:right; font-size:20px;">
                @if (User.Identity is not null)
                {
                    if (User.Identity.IsAuthenticated)
                    {
                        <a asp-controller="Basket" asp-action="Add" style="margin-right:30px;">Add To Basket</a>
                        <a asp-controller="Basket" asp-action="Show">Show Basket</a>
                    }   
                }
            </div>
        </form>
    </div>
</section>

<div class="container">
    <div class="row">
        <br />
        @if(ViewBag.BasketInoperativeMsg != null)
        {
            <div class="alert alert-warning" role="alert">
                &nbsp;@ViewBag.BasketInoperativeMsg
            </div>
        }
    </div>

    @if (Model.CatalogItems.Count() > 0)
    {
    <partial name="_pagination" for="PaginationInfo" />

    <div class="esh-catalog-items row">
        @foreach (var catalogItem in Model.CatalogItems)
            {
        <div class="esh-catalog-item col-md-4">
            <partial name="_product" model="catalogItem" />
        </div>
            }
    </div>

    <partial name="_pagination" for="PaginationInfo" />
    }
    else
    {
    <div class="esh-catalog-items row">
        <p>THERE ARE NO GAMES THAT MATCH YOUR SEARCH</p>
    </div>
    }
</div>

Website/MVC/Views/Catalog/_pagination.cshtml
@model MVC.ViewModels.PaginationInfo

<div class="esh-pager">
    <div class="container">
        <article class="esh-pager-wrapper row">
            <nav>
                <a class="esh-pager-item esh-pager-item--navigable @Model.PreviousPage"
                    id="Previous"                    
                    asp-controller="Catalog"
                    asp-action="Index"
                    asp-route-page="@(Model.CurrentPage-1)"
                    asp-route-itemsPage="@(Model.ItemsPerPage)"
                    aria-label="Previous">
                    Previous
                </a>

                <span class="esh-pager-item">
                    Showing not more than @Model.ItemsPerPage products out of @Model.TotalItems - Page @(Model.CurrentPage + 1) - @Model.TotalPages
                </span>

                <a class="esh-pager-item esh-pager-item--navigable @Model.NextPage"
                    id="Next"                    
                    asp-controller="Catalog"
                    asp-action="Index"
                    asp-route-page="@(Model.CurrentPage+1)"
                    asp-route-itemsPage="@(Model.ItemsPerPage)"
                    aria-label="Next">
                    Next
                </a>
            </nav>
        </article>
    </div>
</div>

Website/MVC/Views/Catalog/_product.cshtml
@model CatalogItem


<form>

    <img class="esh-catalog-thumbnail" src="@Model.PictureUrl" />

    <div class="esh-catalog-name">
        <span>@Model.Name</span>
    </div>
    <div class="esh-catalog-price">
        <span>@Model.Price.ToString("N2")</span>
    </div>
    <input type="hidden" asp-for="@Model.Id" name="id" />
</form>